// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnNpiVbS8e9Pwh3G5wgPM04w2_QA_jFcU',
    appId: '1:575139756096:web:2d6775270da1f6d75b07a5',
    messagingSenderId: '575139756096',
    projectId: 'party-games-canada',
    authDomain: 'party-games-canada.firebaseapp.com',
    storageBucket: 'party-games-canada.firebasestorage.app',
    measurementId: 'G-CG8J85WZCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp48whMoVYrOJoOPWOOV_nTzUFO9_deFU',
    appId: '1:575139756096:android:045f282c386ad3255b07a5',
    messagingSenderId: '575139756096',
    projectId: 'party-games-canada',
    storageBucket: 'party-games-canada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc-37XzG43fEbHCoB3iIO0HWn5hBRunSg',
    appId: '1:575139756096:ios:e71632742fe2df8f5b07a5',
    messagingSenderId: '575139756096',
    projectId: 'party-games-canada',
    storageBucket: 'party-games-canada.firebasestorage.app',
    iosBundleId: 'com.hadenhiles.partygames',
  );
}
